title: 'MAR Greenland'
description: 'Greenland ice sheet reconstructions (2000-2021) from the regional climate model MAR'
recipes:
  - id: mar-greenland
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'Xavier Fettweis'
      description: 'Paper with description of the regional climate model MAR'
      roles:
        - licensor
      url: https://tc.copernicus.org/articles/11/1015/2017/
  license: 'CC-BY-4.0'
maintainers:
  - name: 'Raf Antwerpen'
    orcid: '0000-0002-2313-260X'
    github: raf-antwerpen
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
